### PR TITLE
Refactore of BSD/Mac OS X support for cleaner integration.

### PR DESCRIPTION
**Pull request by spbruner**
This was just some cleanup on the work I did the other day.

### CODE REVIEW

**Comment by wolkykim** [comment]
I'd rather like the previous #ifdef version then introducing a new platform.c file. It's a kind of benefit we have that providing a single core file for the core part for the portability, unless we gets a great reason to split it into multiple files, we should try to keep it as a single file. Can we stick to the #ifdef version?

**Comment by spbruner** [comment]
Of course.

My thinking was that if we get Windows support worked through that you'd have a whole lot more platform specific code, which in turns means more #ifdef'ing. But we can always cross that bridge when we come to it since I personally have no interest in working on Windows support.

Go ahead and close the pull request if that's your preference. I can always branch to keep a copy (not that it was hard) and then revert my master to be inline with upstream.

**Comment by wolkykim** [comment]
Can you do another PR for the contributor list?

**Comment by spbruner** [comment]
Working on it now. I'll close this PR and issue a new.

**Pull request closed without merging**
